puts "The two methods I've chosen are .include & ! "
puts ""
puts "      ****include****"
puts "Definition: '.include?' returns true if str contains a given str or char."
puts "The foundation for other awesome methods, such as Delete."
puts "Above all, I like it because it is a fairly often task to parse a string variable for a given value."
puts ""
puts "Example:"
my_name = "Kevin"
my_name.include? "K"
puts "my_name = 'Kevin'"
puts "my_name.include? 'K' => returns true"
puts ""
puts ""
puts "      ****!****"
puts "Definition: '!' modifies the original object value permanently"
puts "Both ! and the absence of ! allow me to complete tasks I would have to account"
puts "for with a temporary object structure."
puts "The ability to use ! makes code a lot cleaner as well."
puts ""
puts "Example:"
puts "my_name = 'Kevin'"
puts "my_name.upcase => 'KEVIN' "
puts "my_name.upcase! => 'KEVIN' now my_name has changed"